# Generated by Django 4.2.4 on 2023-08-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
        migrations.RemoveField(
            model_name='object',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='object',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='object',
            name='prodapp',
        ),
        migrations.RemoveField(
            model_name='object',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='object',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
