# Generated by Django 4.2.1 on 2023-08-16 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_image_object_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='date_found',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='object',
            name='place_found',
            field=models.CharField(default='Block 1', max_length=100),
        ),
    ]
