# Generated by Django 4.2.1 on 2023-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_object_place_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='image',
            field=models.ImageField(upload_to='\\product'),
        ),
        migrations.AlterField(
            model_name='object',
            name='place_range',
            field=models.CharField(max_length=100),
        ),
    ]
