# Generated by Django 4.2.1 on 2023-10-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_object_object_recovered_object_object_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='brands',
            field=models.CharField(default='Unkwown', max_length=100),
        ),
    ]
