# Generated by Django 4.2.1 on 2023-11-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='requests_amount',
            field=models.IntegerField(default=0),
        ),
    ]
