# Generated by Django 4.2.4 on 2023-08-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_object_brands_object_color_object_hour_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Teal', 'Teal'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Lime', 'Lime'), ('Indigo', 'Indigo'), ('Aqua', 'Aqua'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Turquoise', 'Turquoise'), ('Violet', 'Violet'), ('Coral', 'Coral'), ('Slate', 'Slate'), ('Crimson', 'Crimson'), ('Fuchsia', 'Fuchsia'), ('Mint', 'Mint'), ('Salmon', 'Salmon'), ('Beige', 'Beige'), ('Tan', 'Tan'), ('Khaki', 'Khaki'), ('Lavender', 'Lavender'), ('Plum', 'Plum'), ('Steel Blue', 'Steel Blue'), ('Forest Green', 'Forest Green'), ('Midnight Blue', 'Midnight Blue'), ('Tomato', 'Tomato'), ('Dark Slate Gray', 'Dark Slate Gray'), ('Saddle Brown', 'Saddle Brown')], default='Technology', max_length=100),
        ),
    ]
