# Generated by Django 4.2.3 on 2023-11-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='user_claimer',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='Claim_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='_@eafit.edu.co', max_length=254)),
                ('time_initial', models.TimeField()),
                ('time_final', models.TimeField()),
                ('date_lost', models.DateField()),
                ('extra_data', models.TextField(blank=True)),
                ('object_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.object')),
            ],
            options={
                'unique_together': {('user_email', 'object_related')},
            },
        ),
    ]
