# Generated by Django 4.2.1 on 2023-11-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_object_requests_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='requests_amount',
            new_name='complaints_amount',
        ),
    ]
