# Generated by Django 4.2.3 on 2023-11-11 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_object_user_claimer_claim_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_found', models.CharField(choices=[('Block 1', 'Block 1'), ('Block 3', 'Block 3'), ('Block 4', 'Block 4'), ('Block 5', 'Block 5'), ('Block 6', 'Block 6'), ('Block 7', 'Block 7'), ('Block 8', 'Block 8'), ('Block 9', 'Block 9'), ('Block 10', 'Block 10'), ('Block 12', 'Block 12'), ('Block 13', 'Block 13'), ('Block 14', 'Block 14'), ('Block 15', 'Block 15'), ('Block 16', 'Block 16'), ('Block 17', 'Block 17'), ('Block 18', 'Block 18'), ('Block 19', 'Block 19'), ('Block 20', 'Block 20'), ('Block 21', 'Block 21'), ('Block 23', 'Block 23'), ('Block 26', 'Block 26'), ('Block 27', 'Block 27'), ('Block 28', 'Block 28'), ('Block 29', 'Block 29'), ('Block 30', 'Block 30'), ('Block 32', 'Block 32'), ('Block 33', 'Block 33'), ('Block 34', 'Block 34'), ('Block 35', 'Block 35'), ('Block 37', 'Block 37'), ('Block 38', 'Block 38'), ('Block 39', 'Block 39'), ('Argos Block', 'Argos Block'), ('Main Cafeteria', 'Main Cafeteria'), ('Cafeteria 2', 'Cafeteria 2'), ('North Parking Lot', 'North Parking Lot'), ('South Parking Lot', 'South Parking Lot'), ('Guayabos Parking Lot', 'Guayabos Parking Lot'), ('Synthetic fields - Main Cafeteria', 'Synthetic fields - Main Cafeteria'), ('Synthetic fields - North Parking Lot', 'Synthetic fields - North Parking Lot')], default='Block 1', max_length=100)),
                ('date_found', models.DateField(default=datetime.date.today)),
                ('brands', models.CharField(default='Unkwown', max_length=100)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Teal', 'Teal'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Lime', 'Lime'), ('Indigo', 'Indigo'), ('Aqua', 'Aqua'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Turquoise', 'Turquoise'), ('Violet', 'Violet'), ('Coral', 'Coral'), ('Slate', 'Slate'), ('Crimson', 'Crimson'), ('Fuchsia', 'Fuchsia'), ('Mint', 'Mint'), ('Salmon', 'Salmon'), ('Beige', 'Beige'), ('Tan', 'Tan'), ('Khaki', 'Khaki'), ('Lavender', 'Lavender'), ('Plum', 'Plum'), ('Steel Blue', 'Steel Blue'), ('Forest Green', 'Forest Green'), ('Midnight Blue', 'Midnight Blue'), ('Tomato', 'Tomato'), ('Dark Slate Gray', 'Dark Slate Gray'), ('Saddle Brown', 'Saddle Brown')], default='Block 1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistorySearches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='_@eafit.edu.co', max_length=254)),
                ('quantity', models.IntegerField()),
                ('object_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.search')),
            ],
        ),
    ]
