# Generated by Django 4.2.4 on 2023-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_object_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Keys', 'Keys'), ('Books', 'Books'), ('Water Bottles', 'Water Bottles'), ('Headphones', 'Headphones'), ('Lunchboxes', 'Lunchboxes'), ('Clothes', 'Clothes'), ('Accessories', 'Accessories')], default='Technology', max_length=100),
        ),
    ]
