# Generated by Django 4.2.4 on 2023-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_object_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='place_range',
            field=models.CharField(default='Blocks 1-10', max_length=100),
        ),
    ]
