# Generated by Django 4.2.3 on 2023-11-11 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_search_historysearches'),
    ]

    operations = [
        migrations.AddField(
            model_name='historysearches',
            name='date_searched',
            field=models.DateField(default=datetime.date(2023, 11, 11)),
        ),
    ]
