# Generated by Django 4.2.3 on 2023-11-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_object_user_claimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='user_comment',
            field=models.TextField(blank=True),
        ),
    ]
