# Generated by Django 4.2.3 on 2023-11-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_object_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='user_comment',
        ),
    ]
