# Generated by Django 4.2.1 on 2023-11-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_requests_amount_object_complaints_amount'),
        ('app', '0009_remove_object_user_comment'),
    ]

    operations = [
    ]
