# Generated by Django 4.2.1 on 2023-11-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20231112_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='user_claimer',
        ),
        migrations.DeleteModel(
            name='Claim_Complaint',
        ),
    ]
